### ISSUE TITLE
zlux-server startup Cannot find module './assets/i18n/log/messages_undefined.json'

### ISSUE THREAD

**Issue by OnnoVdT** [zowe/zowe-install-packaging#1136]
**Describe the bug**

Zowe 1.9 staging build 540 (Feb21) startup shows

```
2020-02-21 23:13:46.609 <ZWED:16974359> ZWESVUSR INFO (_zsf.cluster,native array.js:958) ZWED0029I - Worker 0 pid 16974359
ZWED0156W - 1 function initLoggerMessages - ERROR -  { Error: Cannot find module './assets/i18n/log/messages_undefined.json'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at require (internal/module.js:20:19)
    at Object.initLoggerMessages (/shr/usr/lpp/zowe/components/app-server/share/zlux-server-framework/lib/util.js:48:19)
    at new Server (/shr/usr/lpp/zowe/components/app-server/share/zlux-server-framework/lib/index.js:34:8)
    at ClusterManager.createProxyServerWorker (/shr/usr/lpp/zowe/components/app-server/share/zlux-server-framework/lib/clusterManager.js:428:25)
    at ClusterManager.start (/shr/usr/lpp/zowe/components/app-server/share/zlux-server-framework/lib/clusterManager.js:540:10)
    at Object.<anonymous> (/shr/usr/lpp/zowe/components/app-server/share/zlux-app-server/lib/zluxCluster.js:16:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9) code: 'MODULE_NOT_FOUND' 
```

**Expected behavior**

No error

**Comment by OnnoVdT** [comment]
@stevenhorsman I do not know who to assign this too, but I think you do, so I''l assign to you and you can pass the bucket.

**Comment by stevenhorsman** [comment]
Issue moved to [zowe/zlux #400](https://github.com/zowe/zlux/issues/400) via [**ZenHub**](https://www.zenhub.com/)
