### ISSUE TITLE
verify-authenticity gets AccessDeniedException on unredable file

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#1424]
**Describe the bug**
If a file in the runtime does not have read permission, zowe-verify-authenticity.sh throws a 
`java.nio.file.AccessDeniedException`.

**To Reproduce**
1. Set read permission OFF in any file in runtime
2. Run `zowe-verify-authenticity.sh`
3. See error
```
/u/tstradm/hash:>zowe-verify-authenticity.sh -r /u/stevenh/1369/runtime/ -h . >
zowe-verify-authenticity.sh started
Error: Default refPath ./../fingerprint does not exist or is not a directory
/u/tstradm/hash:>zowe-verify-authenticity.sh -r /u/stevenh/1369/runtime/ -h . -f .
zowe-verify-authenticity.sh started
Info: Logging to /u/tstradm/zowe/fingerprint/zowe-verify-authenticity.log
Info: zoweVersion = 1.12.0
Info: Gathering files ...
Info: Calculating hashes ...
java.nio.file.AccessDeniedException: ./bin/utils/zosmfHttpRequest.js
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:96)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:114)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:119)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:226)
        at java.nio.file.Files.newByteChannel(Files.java:372)
        at java.nio.file.Files.newByteChannel(Files.java:418)
        at java.nio.file.Files.readAllBytes(Files.java:3163)
        at HashFiles.readAllBytesJava7(HashFiles.java:42)
        at HashFiles.main(HashFiles.java:60)
Info: Comparing results ...
Info: Number of files different =  850
Info: Number of files extra     =  19
Info: Number of files missing   =  75
Error: Verification FAILED
Info: Result files and script log are in directory /u/tstradm/zowe/fingerprint
zowe-verify-authenticity.sh ended
```
**Expected behavior**
No java errors

**Additional context**
A developer may have created an unreadable file during a test.

The zowe-verify-authenticity.sh script continues and completes successfully.

**Comment by Martin-Zeithaml** [comment]
In v2, there is `try & catch` for reading file, e.g.: 
`IOException reading file ./bin/README.md`, no java errors.
