### ISSUE TITLE
netstat may fail on some servers with network util test

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#1441]
**Describe the bug**

On some servers (very common on SVL images), when you run `netstat -P 10443`, you will receive a failure:

```
$ netstat -P 10443
EZZ2376I Could not determine TCPIPjobname, using default of 'INET'
EZZ2377I Could not establish affinity with INET (1011/11B3005A) - can not provide the requested option information
$ echo $?
16
```

This caused test case failure of this:

```
AssertionError: expected 16 to equal 0
    at Object.executeCommandWithNoError (test/install/ssh-helper.js:50:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
+ expected- actual

- 16
+ 0
let found_unbound = false;
while (! found_unbound && unbound_port <= 65535) {
  const report = await sshHelper.executeCommandWithNoError(`netstat -P ${unbound_port}`);
  if (report.split(/\r?\n/).length <= 3) {
    // netstat report of format:
    // MVS TCP/IP NETSTAT CS V2R3       TCPIP Name: TCPIP           11:49:59
    // User Id  Conn     State
    // -------  ----     -----
    found_unbound = true;
  } else {
    unbound_port++;
  }
}
```

Due to incorrect configuration of the server. The server may have it fixed by adding `RESOLVER_CONFIG` to the environment, but this is not recognized by the SSH connection created by the test case.

**To Reproduce**

1. Need a server to have Zowe installed, and has TCPIP configuration issue described above.
2. Run sanity test `tests/sanity/test/install/test-network-utils.js`.

**Expected behavior**

The SSH connection generated by the test should be able to load the environment variable defined in `/etc/profile` or `~/.profile`.

**Comment by jackjia-ibm** [comment]
I would see this is more like a system configuration issue rather than we need to do anything on our side. The `netstat` command should work properly and shouldn't be resolved by zowe install/configure.

This is a way to configure it other than `RESOLVER_CONFIG` environment variable. Kudos to @NayerNajafi 

The resolver function uses its own address space that is called RESOLVER. By default the RESOLVER address space is created by z/OS UNIX System Services initialization.

If we want to make use of other than the resolver default services the resolver must be customized. This will require

1. to create a resolver START procedure:   `USER.PROCLIB(RESOLVER)` :

```
//RESOLVER PROC PARMS='CTRACE(CTIRES00)'                     
//EZBREINI EXEC PGM=EZBREINI,REGION=0M,TIME=1440,PARM=&PARMS 
//SETUP   DD   DSN=USER.PARMLIB(TCPRESOL),DISP=SHR,FREE=CLOSE
```

2. to create the `RESOLVER` setup file which contains the resolver setup statements:  `USER.PARMLIB(TCPRESOL)` :

```
DEFAULTTCPIPDATA('USER.PARMLIB(TCPDATA)')
NOCOMMONSEARCH                           
CACHE                                    
NOCACHEREORDER                           
CACHESIZE(200M)                          
MAXTTL(2147483647)                       
UNRESPONSIVETHRESHOLD(25)                
```

3. change `BPXPRMxx` PARMLIB member to include statement `RESOLVER_PROC(procname)` where procname is the resolver `START` procedure member name
4. IPL the system
