### ISSUE TITLE
Error while using external CA to deploy Zowe 1.15.0

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zowe-install-packaging#1736]
When using external CA to deploy Zowe 1.15.0, we see similar error while login to desktop as following
 
```
2020-07-28 02:13:43.203 <ZWED:262486> IZUSVR WARN (org.zowe.zlux.auth.safsso,apimlHandler.js:263) APIML query error: self signed certificate in certificate chain
2020-07-28 02:13:43.288 <ZWED:262486> IZUSVR WARN (org.zowe.zlux.auth.safsso,apimlHandler.js:337) APIML login has failed:
2020-07-28 02:13:43.288 <ZWED:262486> IZUSVR WARN (org.zowe.zlux.auth.safsso,apimlHandler.js:338)  Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
```
 
We added following parameter into instance.env for external root certificate and intermediate certificates in PEM format, as Sean and Tim suggested, to work around the issue.
 
```
ZWED_node_https_certificateAuthorities="/path/to/zowe/keystore/local_ca/localca.cer-ebcdic","/path/to/carootcert.pem","/path/to/caintermediatecert.pem"
```

Tim and Sean is currently working on this issue, I open this for tracking purpose.

**Comment by rjmaomao** [comment]
Tim's Troubleshooting tip on this issue. 
https://github.com/zowe/docs-site/issues/1448

**Comment by rjmaomao** [comment]
Tried 1.17.0, there's no error any more.

**Comment by jackjia-ibm** [comment]
Seems this was solved so will close. Please re-open if it's not.
