### ISSUE TITLE
APIML not running in docker image

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zowe-install-packaging#1887]
The APIML (specifically gateway) doesn't start up properly and the docker log shows:

```
Exception in thread "main" java.lang.IllegalArgumentException: File /usr/include/java_classes/IRRRacf.jar must exist
            at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.openIfNecessary(RandomAccessDataFile.java:234)
            at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.<init>(RandomAccessDataFile.java:216)
            at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.<init>(RandomAccessDataFile.java:206)
            at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:49)
            at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:88)
            at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:60)
            at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:56)
            at org.springframework.boot.loader.PropertiesLauncher.getArchive(PropertiesLauncher.java:500)
            at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(PropertiesLauncher.java:476)
            at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(PropertiesLauncher.java:446)
            at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
            at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
```
 In stderr.
            
It looks like this might have something to do with https://github.com/zowe/api-layer/pull/1010/files given that there aren't other changes related to IRRRacf.jar that we can find.

**Comment by stevenhorsman** [comment]
cc @jalel01 @1000TurquoisePogs @NakulManchanda

**Comment by balhar-jakub** [comment]
@jandadav Any idea what might be the issue with this? I remember you were working on the -cp change.

**Comment by jandadav** [comment]
This is probably thanks to the fact that Gateway wants to load IRRRacf.jar. 
The start script says this:
```    -Dloader.path=${COMMON_LIB},/usr/include/java_classes/IRRRacf.jar \```
If the JAR is not in Docker, the loader might fail. You suggest it's related to IRRRacf.jar. Do you see a failure in the log that says which file? It's not apparent from the snippet.

Assuming the problem is what I think it is: possible solutions:
1) put a dummy  IRRRacf.jar in where the real one should be
2) condition the start script based on OS/environment
3) have a different start script for docker
4) have entirely different package for docker

Any opinions? I think that 2) seems feasible. Is there a variable that we can hook on?
Or would something like this work on the start script? 
```
if [ `uname` = "OS/390" ]; then
    .... do magic
fi
```

**Comment by stevenhorsman** [comment]
@jandadav - Sorry David, I messed up the GFM formatting, so the first line didn't show. Fixed that now. If you want the full details you can take a look at the logs for last night's staging build: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/staging/952/consoleFull and search for 'get docker logs using docker ps'

With respect to a fix - I think option 2 is probably the best approach for the short-term and `uname` has been used elsewhere. I don't think there is a available variable during starting the components at the moment, but @jackjia-ibm might know better.

**Comment by jandadav** [comment]
Ok, I will go and add it to codebase.

**Comment by jandadav** [comment]
it's in 1.20.0-SNAPSHOT now. Let's wait for the nightly build

**Comment by jackjia-ibm** [comment]
@jandadav @stevenhorsman you are right, there is no global variable for this purpose yet. We can add if this makes component easier.

**Comment by stevenhorsman** [comment]
This is working with the lastest APIML build in staging: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/staging/954/
Thanks!
