### ISSUE TITLE
Zowe 1.19.1 zowe-setup-certificates.sh script failed if not executed from correct dir

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zowe-install-packaging#2030]
Hi,

I'm installing zowe 1.19.1 on our zOS images. I downloaded the pax file and then installed runtime. Then I hit following error while running certificate setup scripts.  I noticed the the `../` between `1.19.1` and `components` in following error message  **File /Z2/var/zowert/1.19.1/../components/apiml-common-lib/bin/api-layer-lite-lib-all.jar must exist**  . I executed the script under dir /Z2/var/zowert/1.19.1, but seems the script assumed that I was executing it under /Z2/var/zowert/1.19.1/bin. Then I change dir to /Z2/var/zowert/1.19.1/bin and execute the script again and everything's fine this time. Could you please help to take a look? Since there's no doc state under which dir should this script be executed, I think the script should handle the file location properly. 
By the way, I didn't hit the same issue in previous zowe version even when execute script under /Z2/var/zowert/1.1x.x

```
138:/Z2/var/zowert/1.19.1 $ bin/zowe-setup-certificates.sh -p /zowe/keystore/zowe-setup-certificates.env
Log file created: /u/renjing/zowe/logs/zowe-setup-certificates-2021-03-19-00-07-20.log
Loading default variables from /Z2/var/zowert/1.19.1/bin/zowe-setup-certificates.env file.
Loading /zowe/keystore/zowe-setup-certificates.env file and overriding default variables.
error : dig found hostname z2pub.pok.stglabs.ibm.com and IP but IP did not match 9.114.33.20
  ZOWE_IP_ADDRESS    variable value=9.114.33.20
  ZOWE_EXPLORER_HOST variable value=z2pub.pok.stglabs.ibm.com
Creating certificates and keystores... STARTED
z/OSMF certificate fingerprint:
Owner: CN=ZPETPLX2ZOSMF.POK.STGLABS.IBM.COM, OU=ZMZ2, O=IBM
	 MD5:  47:D1:69:31:0B:8D:2F:20:F5:94:7F:9E:04:3B:37:B5
	 SHA1: A5:84:98:67:78:74:DE:00:FD:D6:28:63:1C:07:8A:D0:45:0E:E6:A7
	 SHA256: D2:E0:DD:AC:2B:3C:D5:AC:7B:56:84:B7:5C:1E:A3:85:A6:DB:65:36:B6:43:71:02:A5:06:41:C9:82:95:DD:5A
Owner: CN="z/OSMF CertAuth for Security           Domain", OU=ZMZ2
	 MD5:  03:9E:E8:36:7D:2C:E0:77:26:2F:81:45:BF:B7:3C:A0
	 SHA1: 95:DD:76:17:00:0F:6C:EB:93:D7:96:AD:BA:69:84:41:25:14:FD:C8
	 SHA256: 0B:3D:70:38:CC:E3:F3:44:DA:95:88:C5:2C:FA:AA:EA:9A:6E:FD:87:3B:FE:ED:8B:84:D4:33:20:A7:94:E9:10
Exception in thread "main" java.lang.IllegalArgumentException: File /Z2/var/zowert/1.19.1/../components/apiml-common-lib/bin/api-layer-lite-lib-all.jar must exist
	at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.openIfNecessary(RandomAccessDataFile.java:234)
	at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.<init>(RandomAccessDataFile.java:216)
	at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.<init>(RandomAccessDataFile.java:206)
	at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:49)
	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:88)
	at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:60)
	at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:56)
	at org.springframework.boot.loader.PropertiesLauncher.getArchive(PropertiesLauncher.java:500)
	at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(PropertiesLauncher.java:476)
	at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(PropertiesLauncher.java:446)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
apiml_cm.sh --action trust-zosmf has failed. See /u/renjing/zowe/logs/zowe-setup-certificates-2021-03-19-00-07-20.log for more details
ERROR: z/OSMF is not trusted by the API Mediation Layer. Make sure ZOWE_ZOSMF_HOST and ZOWE_ZOSMF_PORT variables define the desired z/OSMF instance.
ZOWE_ZOSMF_HOST=zpetplx2zosmf.pok.stglabs.ibm.com   ZOWE_ZOSMF_PORT=34211
You can also specify z/OSMF certificate explicitly in the ZOSMF_CERTIFICATE environmental variable in the zowe-setup-certificates.env file.
```

Thanks!

**Comment by jackjia-ibm** [comment]
This should be fxied with PR-2062. Please re-open the issue if it's not.
