### ISSUE TITLE
Problem with Certificate job with release 1.20.1

### ISSUE THREAD

**Issue by shgordon2222** [zowe/zowe-install-packaging#2060]
Skipping from release 1.12 to release 1.20.1

Running Certificate job and getting error.

From the Job STDERR DD:

Exception in thread "main" java.lang.IllegalArgumentException: File /usr_lpp/zowe/../components/apiml-common-lib/bin/api-layer-lite-lib-all.jar must exist
 at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.openIfNecessary(RandomAccessDataFile.java:234)
 at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.<init>(RandomAccessDataFile.java:216
 at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.<init>(RandomAccessDataFile.java:206)
 at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:49)
 at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:88)         
 at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:60)
 at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:56)
 at org.springframework.boot.loader.PropertiesLauncher.getArchive(PropertiesLauncher.java:500)
 at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(ProprtiesLauncher.java:476)
 at org.springframework.boot.loader.PropertiesLauncher.getClassPathArchives(PropertiesLauncher.java:446)
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)           
 at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
apiml_cm.sh --action trust-zosmf has failed. See /global/zowe/logs/zowe-setup-certificates-2021-04-02-07-37-44.log for more details
ERROR: z/OSMF is not trusted by the API Mediation Layer. Make sure ZOWE_ZOSMF_HOST and ZOWE_ZOSMF_PORT variables define the desired z/OSMF instance.

From Log:

Retrieves z/OSMF JWT public key and stores it to /global/zowe/keystore/localhost/localhost.keystore.jwtsecret.pem
apiml_cm.sh --action trust-zosmf returned: 1                                    

Appears to me that the issue is within the apiml_cm.sh
under the function zosmf_jwt_public_key 

-cp "${BASE_DIR}/../components/gateway/bin/gateway-service-lite.jar" \  
-Dloader.path="../components/apiml-common-lib/bin/api-layer-lite-lib-all.jar" \

What I do not understand is why it cannot find the all.jar

Under directory /usr_lpp/zowe/components/apiml-common-lib/bin  I do an    ls -l    and get the following:

-rwxr-xr-x   1 BPXROOT  $9AUS385 86465856 Mar 16 13:38 api-layer-lite-lib-all.jar   

Any help would be appreciated.

**Comment by jackjia-ibm** [comment]
Duplicates of #2030, please re-open if you believe it's not the same case.
