### ISSUE TITLE
Out-of-memory error in ZOWESVR3 on zD&T 

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#236]
```
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/01/07 15:03:30 - please wait.                                         
JVMDUMP032I JVM requested System dump using 'IZUSVR.JVM.ZOWESVR3.D190107.T150330.X&DS' in response to an event                                                  
IEATDUMP in progress with options SDATA=(LPA,GRSQ,LSQA,NUC,PSA,RGN,SQA,SUM,SWA,TRT)                                                                             
IEATDUMP success for DSN='IZUSVR.JVM.ZOWESVR3.D190107.T150330.X&DS'                                                                                             
JVMDUMP040I System dump written to dataset(s) using name template IZUSVR.JVM.ZOWESVR3.D190107.T150330.X&DS                                                      
JVMDUMP032I JVM requested Heap dump using '/zaas1/zowe/0.9.5/explorer-server/wlp/usr/servers/Atlas/heapdump.20190107.150330.83952534.0002.phd' in response to an
JVMDUMP010I Heap dump written to /zaas1/zowe/0.9.5/explorer-server/wlp/usr/servers/Atlas/heapdump.20190107.150330.83952534.0002.phd                             
JVMDUMP032I JVM requested Java dump using '/zaas1/zowe/0.9.5/explorer-server/wlp/usr/servers/Atlas/javacore.20190107.150330.83952534.0003.txt' in response to an
JVMDUMP010I Java dump written to /zaas1/zowe/0.9.5/explorer-server/wlp/usr/servers/Atlas/javacore.20190107.150330.83952534.0003.txt                             
JVMDUMP032I JVM requested Snap dump using '/zaas1/zowe/0.9.5/explorer-server/wlp/usr/servers/Atlas/Snap.20190107.150330.83952534.0004.trc' in response to an eve
JVMDUMP010I Snap dump written to /zaas1/zowe/0.9.5/explorer-server/wlp/usr/servers/Atlas/Snap.20190107.150330.83952534.0004.trc                                 
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".                                                                               
[ERROR   ] Error occurred during error handling, give up!                                                                                                       
Java heap space                                                                                                                                                 
[ERROR   ] SRVE0777E: Exception thrown by application class 'org.apache.cxf.service.invoker.AbstractInvoker.createFault:162'                                    
org.apache.cxf.interceptor.Fault: Java heap space                                                                                                               
 at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)                                                                        
 at [internal classes]                                                                                                                                          
Caused by: java.lang.OutOfMemoryError: Java heap space                                                                                                          
 at java.lang.StringBuilder.ensureCapacityImpl(StringBuilder.java:772)                                                                                          
 at java.lang.StringBuilder.append(StringBuilder.java:280)                                                                                                      
 at org.apache.cxf.helpers.IOUtils.toString(IOUtils.java:320)                                                                                                   
 at [internal classes]                                                                                                                                          
 at com.ibm.atlas.webservice.services.ZosmfFilesService.getContent(ZosmfFilesService.java:271)                                                                  
 at com.ibm.atlas.webservice.resource.Files.getContent(Files.java:65)                                                                                           
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                 
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)                                                                               
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)                                                                       
 at java.lang.reflect.Method.invoke(Method.java:508)                                                                                                            
 at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:286)                        
 ... 1 more          
```

**Comment by John-A-Davies** [comment]
This server had been running since 13:52 that day.

**Comment by John-A-Davies** [comment]
This error is from ZOWESVR3; Liberty, which is being removed in next release.
