### ISSUE TITLE
Zowe Docker on zCX: ZWED0031W SyntaxError: Unexpected token in JSON at position 0 at JSON.parse 

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/zowe-install-packaging#2370]
**Describe the bug**
I installed Zowe 1.24.0 s390x tar file. I have the following issue when Zowe Docker started on zCX:

```
zowe WARN (_zsf.bootstrap,plugin-loader.js:722) ZWED0031W SyntaxError: Unexpected token in JSON at position 0
    at JSON.parse (<anonymous>)
    at readJSONStringWithComments (/home/zowe/install/components/app-server/share/zlux-server-framework/lib/jsonUtils.js:77:23)
    at Function.JSONUtils.readJSONFileWithComments (/home/zowe/install/components/app-server/share/zlux-server-framework/lib/jsonUtils.js:93:10)
    at Object.exports.parseJSONWithComments (/home/zowe/install/components/app-server/share/zlux-server-framework/lib/jsonUtils.js:110:20)
    at PluginLoader._readPluginDef (/home/zowe/install/components/app-server/share/zlux-server-framework/lib/plugin-loader.js:637:31)
    at PluginLoader.readPluginDefs (/home/zowe/install/components/app-server/share/zlux-server-framework/lib/plugin-loader.js:719:29)
    at PluginLoader.<anonymous> (/home/zowe/install/components/app-server/share/zlux-server-framework/lib/plugin-loader.js:776:23)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/zowe/install/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/zowe/install/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/generators.js:97:49)
    at PluginLoader.loadPlugins (/home/zowe/install/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/generators.js:201:15)
    at Server.<anonymous> (/home/zowe/install/components/app-server/share/zlux-server-framework/lib/index.js:399:29)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/zowe/install/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/zowe/install/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/generators.js:97:49)
    at _drainQueueStep (/home/zowe/install/components/app-server/share/zlux-server-framework/node_modules/bluebird/js/release/async.js:142:12)
2021-10-01 00:36:39.705 <ZWED:3230> zowe WARN (_zsf.bootstrap,plugin-loader.js:723) ZWED0032W - Failed to load org.zowe.explorer-ip.json

```
**To Reproduce**
1. Run start.sh 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jackjia-ibm** [comment]
May revalidate this issue after https://github.com/zowe/zlux-build/pull/91/files is merged.

Or verify with v1.26.0 release.

**Comment by MarkAckert** [comment]
Closing, as this issue is stale and a potential fix was merged in. Please re-open if you still see the issue on 1.26+ .
