### ISSUE TITLE
Authentification failed

### ISSUE THREAD

**Issue by TCOS7** [zowe/zowe-install-packaging#2752]
**Describe the bug**
When we logon on the habilitation page , we have an authentification problème : "Authentification failed for 1 types. Types: ["zss"]."
The Zlux primary page answers correctly and the api médiation layer answer correctly too.
We use a keystore.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/102954460/161516576-70393a2f-28cf-4cc2-8cfd-f91911da7418.PNG)

![Capture](https://user-images.githubusercontent.com/102954460/161516444-1032ddfd-8d41-4e52-baab-53bcfd3d71b8.PNG)

**Desktop (please complete the following information):**
 - OS: z/OS 2.4
 - Browser : chrome Version 90.0.4430.93 (Official Build) (64-bit) 
 - Version : ZOWE 1.27.1
 - Version : nodejs Version 12.18.0
 - Version : Java 8.0-64

**Comment by jackjia-ibm** [comment]
Hi @TCOS7, there are many possibilities may cause this failure. Did you try out guidance of https://docs.zowe.org/stable/troubleshoot/app-framework/app-troubleshoot#cannot-log-in-to-the-zowe-desktop? If it still doesn't work, please ask in #zowe-users OMP Slack channel.

**Comment by GilPen** [comment]
Hello 

We ( with @TCOS7 ) saw the documentation but the recommandations are ok.
 
We also send a message in Open Mainframe Project #zowe-user. We are waiting for their help.

However we did an IP trace and notice that there is no bytes transfering on IP ZSS port 8542 during a logon on ZOWE ZLUX page.

Some messages on the SYSOUT STC ZOWE appears :

2022-04-07 12:52:15.723 <ZWED:33554537> ZWESVUS WARN (_zsf.auth,webauth.js:367) ZWED0003W - User=undefined (org.zowe.zlux.auth.zss): Session authenticate failed. Plugin response: é"success":falseè 
2022-04-07 12:52:16.381 <ZWED:50331741> ZWESVUS WARN (_zsf.apiml,EurekaClient.js:710) Eureka request failed to endpoint https://sysa.dns21.socgen:7553/eureka/apps, next server retry in 60000ms
2022-04-07 12:52:21.596 <ZWED:33554537> ZWESVUS INFO (_zsf.auth,webauth.js:364) ZWED0070I - User=undefined (org.zowe.zlux.auth.trivial): Session authenticate successful. Plugin response: é"success":trueè

Error: self signed certificate in certificate chain           
    at TLSSocket.onConnectSecure (_tls_wrap.js:1506:34)       
    at TLSSocket.emit (events.js:315:20)                      
    at TLSSocket._finishInit (_tls_wrap.js:948:8)             
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) é    
  code: 'SELF_SIGNED_CERT_IN_CHAIN'                           
è         

Regards
Gilles

**Comment by GilPen** [comment]
Hello 

I wanted to deactivate TLS support for ZSS. So I modified the parameter in instance.env to
ZOWE_ZSS_SERVER_TLS=false

And I modified as well the server.json file on workspace directory from https to http :

"http": 	é                            
  "ipAddresses": Ý"127.0.0.1"~,      
  //to be a replacement for zssPort  
  "port": 8542                       
è,  

We come from a 1.20.1 version which doesn't support TLS for ZSS. 

But no success.

Regards
Gilles
