### ISSUE TITLE
truststore issues [minicube]

### ISSUE THREAD

**Issue by christianwohlgemuth** [zowe/zowe-install-packaging#2985]
**Describe the bug**
Pod is not healthy

```
kubernetes]$ kubectl logs -f  api-catalog-646cc5ddcb-hlgdf -n zowe
Defaulted container "api-catalog" out of: api-catalog, init-zowe (init)
2022-08-11 11:27:44 <ZWELS:1> zowe INFO (zwe-internal-start-prepare:343) Zowe version: v2.2.0
2022-08-11 11:27:44 <ZWELS:1> zowe INFO (zwe-internal-start-prepare:344) build and hash: v2.x/rc#189 (7567c9be023e437a9029297172933438170a406b)
2022-08-11 11:27:44 <ZWELS:1> zowe INFO (zwe-internal-start-prepare:360) starting Zowe instance api_catalog_646cc5ddcb_hlgdf with /home/zowe/instance/zowe.yaml ...
2022-08-11 11:27:45 <ZWELS:1> zowe ERROR (zwe-internal-start-prepare,prepare_workspace_directory:85) WARNING: Failed to set permission of some existing files or directories in /home/zowe/instance/workspace:
2022-08-11 11:27:45 <ZWELS:1> zowe ERROR (zwe-internal-start-prepare,prepare_workspace_directory:86) chmod: changing permissions of '/home/zowe/instance/workspace': Operation not permitted
WARNING: <workspace-dir>/app-server/.configs-api_catalog_646cc5ddcb_hlgdf.json doesn't exist
WARNING: <workspace-dir>/caching-service/.configs-api_catalog_646cc5ddcb_hlgdf.json doesn't exist
WARNING: <workspace-dir>/discovery/.configs-api_catalog_646cc5ddcb_hlgdf.json doesn't exist
WARNING: <workspace-dir>/explorer-ip/.configs-api_catalog_646cc5ddcb_hlgdf.json doesn't exist
WARNING: <workspace-dir>/explorer-jes/.configs-api_catalog_646cc5ddcb_hlgdf.json doesn't exist
WARNING: <workspace-dir>/explorer-mvs/.configs-api_catalog_646cc5ddcb_hlgdf.json doesn't exist
WARNING: <workspace-dir>/explorer-uss/.configs-api_catalog_646cc5ddcb_hlgdf.json doesn't exist
WARNING: <workspace-dir>/files-api/.configs-api_catalog_646cc5ddcb_hlgdf.json doesn't exist
WARNING: <workspace-dir>/gateway/.configs-api_catalog_646cc5ddcb_hlgdf.json doesn't exist
WARNING: <workspace-dir>/jobs-api/.configs-api_catalog_646cc5ddcb_hlgdf.json doesn't exist
/home/zowe/instance/workspace/.env/.instance-api_catalog_646cc5ddcb_hlgdf.env: line 64: 0=Z: command not found
---- snip ----
/home/zowe/runtime/bin/libs/var.sh: line 75: export: `117': not a valid identifier
2022-08-11 11:27:56 <ZWELS:1> zowe INFO (zwe-internal-start-component:72) starting component api-catalog ...
jar file: /home/zowe/runtime/components/api-catalog/bin/api-catalog-services-lite.jar
pid=2936
2022-08-11 11:28:18.435 <ZWEAAC1:main:2936> zowe ERROR (o.z.a.s.HttpsFactory) error
java.io.IOException: keystore password was incorrect
        at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2079)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.apache.http.ssl.SSLContextBuilder.loadKeyMaterial(SSLContextBuilder.java:332)
        at org.zowe.apiml.security.HttpsFactory.loadKeystoreMaterial(HttpsFactory.java:188)
        at org.zowe.apiml.security.HttpsFactory.loadKeyMaterial(HttpsFactory.java:161)
        at org.zowe.apiml.security.HttpsFactory.createSecureSslContext(HttpsFactory.java:211)
        at org.zowe.apiml.security.HttpsFactory.createSecureSslSocketFactory(HttpsFactory.java:240)
        at org.zowe.apiml.security.HttpsFactory.createSslSocketFactory(HttpsFactory.java:85)
        at org.zowe.apiml.security.HttpsFactory.createSecureHttpClient(HttpsFactory.java:66)
        at org.zowe.apiml.product.web.HttpConfig.init(HttpConfig.java:145)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:410)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:410)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:693)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
        at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:111)
        at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:92)
        at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:101)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:255)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1135)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:410)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
        at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:111)
        at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:92)
        at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:101)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:255)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1160)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1135)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:270)
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:762)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:567)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
        at org.zowe.apiml.apicatalog.ApiCatalogApplication.main(ApiCatalogApplication.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
        ... 132 common frames omitted
2022-08-11 11:28:18.534 <ZWEAAC1:main:2936> zowe ERROR (o.z.a.s.HttpsFactory) ZWEAM400E Error initializing SSL Context: 'keystore password was incorrect'

```

**To Reproduce**
1. setup minicube as non-root user
2. download & unpack k8s scripts [https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/2.2.0/zowe-containerization-2.2.0.zip]
3. populate the samples/certificates-secret.yaml
4. kubectl apply -f common/zowe-ns.yaml
5. kubectl apply -f common/zowe-sa.yaml
6. change storageClassName to 'standard'
7. kubectl apply -f samples/workspace-pvc.yaml
8. kubectl apply -f workloads/api-catalog-deployment.yaml

**debug**
`kubectl exec -it -n zowe api-catalog-646cc5ddcb-hlgdf -- bash`

```
zowe@api-catalog-646cc5ddcb-hlgdf:/component$  ps ax | more
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 /bin/sh /home/zowe/runtime/bin/zwe internal start -c /home/zowe/instance/zowe.yaml
   1908 ?        S      0:00 /bin/sh /home/zowe/runtime/bin/zwe internal start -c /home/zowe/instance/zowe.yaml
   2926 ?        S      0:00 /bin/sh
   2936 ?        Sl     0:15 java -Xms16m -Xmx512m -Dibm.serversocket.recover=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/tmp -Dspring.profiles.active= -Dapiml.service.hostname=172-17-0-3.zowe.pod.cluster.local -Dapiml.service.port=7552
 -Dapiml.service.discoveryServiceUrls=https://discovery-0.discovery-service.zowe.svc.cluster.local:7553/eureka/ -Dapiml.service.gatewayHostname=172-17-0-3.zowe.pod.cluster.local -Dapiml.logs.location=/home/zowe/instance/logs -Dapiml.disc
overy.staticApiDefinitionsDirectories=/home/zowe/instance/workspace/api-mediation/api-defs -Dapiml.security.ssl.verifySslCertificatesOfServices=true -Dapiml.security.ssl.nonStrictVerifySslCertificatesOfServices=true -Dapiml.security.auth
orization.provider= -Dapiml.security.authorization.endpoint.enabled=false -Dapiml.security.authorization.endpoint.url=https://172-17-0-3.zowe.pod.cluster.local:7554/zss/api/v1/saf-auth -Dapiml.security.authorization.resourceClass=ZOWE -D
spring.profiles.include= -Dserver.address=0.0.0.0 -Dserver.ssl.enabled=true -Dserver.ssl.keyStore=**/home/zowe/keystore/keystore.p12** -Dserver.ssl.keyStoreType=PKCS12 -Dserver.ssl.keyStorePassword=**password** -Dserver.ssl.keyAlias=localhost -D
server.ssl.keyPassword=password -Dserver.ssl.trustStore= -Dserver.ssl.trustStoreType=PKCS12 -Dserver.ssl.trustStorePassword= -Djava.protocol.handler.pkgs=com.ibm.crypto.provider -Dloader.path=apiml-common-lib/bin/api-layer-lite-lib-all.j
ar -Djava.library.path=:/lib:/usr/lib:/bin:/bin/classic:/bin/j9vm:/lib/s390/classic:/lib/s390/default:/lib/s390/j9vm:../common-java-lib/bin/ -jar /home/zowe/runtime/components/api-catalog/bin/api-catalog-services-lite.jar
   2950 pts/0    Ss     0:00 bash
   2957 pts/0    R+     0:00 ps ax
   2958 pts/0    S+     0:00 more
```

```
zowe@api-catalog-646cc5ddcb-hlgdf:/component$ openssl pkcs12 -nokeys -info -in **/home/zowe/keystore/keystore.p12** -passin pass:**password**
MAC: sha256, Iteration 2048
MAC length: 32, salt length: 8
PKCS7 Encrypted data: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
Certificate bag
Bag Attributes
    localKeyID: 78 8A 79 14 B4 40 9A 94 41 34 EA E2 77 96 35 7F 07 34 F0 6A
--- snip data ---
PKCS7 Data
Shrouded Keybag: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
```

**Comment by christianwohlgemuth** [comment]
the truststore/keystore created with openssl don't work.
`openssl pkcs12 -export -inkey <key> -in <certificate> -out keystore.p12`

converting the openssl keystore into a java keystore works
```
openssl pkcs12 -export -inkey <key> -in <certificate> -name localhost -out tmp.p12
keytool -importkeystore -srckeystore tmp.p12 -destkeystore keystore.p12  -srcstoretype pkcs12 -deststoretype pkcs12 -alias localhost
```
