### ISSUE TITLE
Invalid plugin explorer-server-auth during Zowe startup

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#307]
In the Zowe startup, these error will show in the job log:

```
[2019-01-25 21:08:20.178 _unp.bootstrap WARNING] - /zaas1/zowe/explorer-server-auth/ points to an invalid plugin definition, skipping
Error: Plugin com.zowe.explorer.server.auth invalid
    at makePlugin (/zaas1/zowe/zlux-server-framework/js/plugin-loader.js:505:11)
    at PluginLoader.installPlugins (/zaas1/zowe/zlux-server-framework/js/plugin-loader.js:620:24)
    at PluginLoader.loadPlugins (/zaas1/zowe/zlux-server-framework/js/plugin-loader.js:592:10)
    at Server.<anonymous> (/zaas1/zowe/zlux-server-framework/js/index.js:171:23)
    at next (native)
    at tryCatcher (/zaas1/zowe/zlux-server-framework/js/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/zaas1/zowe/zlux-server-framework/js/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/zaas1/zowe/zlux-server-framework/js/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/zaas1/zowe/zlux-server-framework/js/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/zaas1/zowe/zlux-server-framework/js/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/zaas1/zowe/zlux-server-framework/js/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/zaas1/zowe/zlux-server-framework/js/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/zaas1/zowe/zlux-server-framework/js/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/zaas1/zowe/zlux-server-framework/js/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2019-01-25 21:08:20.193 _unp.bootstrap INFO] - Failed to load com.zowe.explorer.server.auth: Error: Plugin com.zowe.explorer.server.auth invalid
```

**Comment by jordanCain** [comment]
explorer-server-auth is currently being removed via the following PRs,

https://github.com/zowe/zlux-app-server/pull/39 & https://github.com/zowe/zlux/pull/66

**Comment by jordanCain** [comment]
Has now been removed from zlux
