### ISSUE TITLE
ZLUX impossible to connect v1.27

### ISSUE THREAD

**Issue by GilPen** [zowe/zowe-install-packaging#3208]
**Describe the bug**
Impossible to connect to ZLUX 
An error message appears : "Authentication failed for 1 types. Types: ["zss"]

**Desktop (please complete the following information):**
 - OS: ZOS 2.4
- ZOWE:  v.1.27.0+20220111
 - Browser : Edge
 - Version : Version 107.0.1418.35 (Official build) (64-bit)

Error message in log file : 
 2022-12-15 01:14:08.407 <ZWED:605> ZWESVUS CRITICAL (_zsf.apiml,apiml.js:301)                                                     
   'Problem making eureka request',                                                                                                 
   Error: self signed certificate in certificate chain                                                                              
       at TLSSocket.onConnectSecure (_tls_wrap.js:1506:34)                                                                          
       at TLSSocket.emit (events.js:315:20)                                                                                         
       at TLSSocket._finishInit (_tls_wrap.js:948:8)                                                                                
       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) é                                                                       
     code: 'SELF_SIGNED_CERT_IN_CHAIN'                                                                                              
   è                                                                                                                                
 ~                                                                                                                                 
 2022-12-15 01:14:08.407 <ZWED:605> ZWESVUS WARN (_zsf.apiml,apiml.js:302) ZWED0005W Error: self signed certificate in certificate chain
     at TLSSocket.onConnectSecure (_tls_wrap.js:1506:34)                                                                            
     at TLSSocket.emit (events.js:315:20)                                                                                           
     at TLSSocket._finishInit (_tls_wrap.js:948:8)                                                                                  
     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) é                                                                         
   code: 'SELF_SIGNED_CERT_IN_CHAIN'                                                                                                
 è                                                                                                                                  
 ZWED0151W - unhandledRejection Error: self signed certificate in certificate chain                                                 
     at TLSSocket.onConnectSecure (_tls_wrap.js:1506:34)                                                                            
     at TLSSocket.emit (events.js:315:20)                                                                                           
     at TLSSocket._finishInit (_tls_wrap.js:948:8)                                                                                  
     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) é                 

However, I'm not using a self certificate but some CA certificates.

[zowe-setup-certificates-2022-12-15.log](https://github.com/zowe/zowe-install-packaging/files/10235341/zowe-setup-certificates-2022-12-15.log)
[zowe-setup-certificates-2022-12-15.txt](https://github.com/zowe/zowe-install-packaging/files/10235342/zowe-setup-certificates-2022-12-15.txt)

In any case, I don't understand why the ZLUX page is displaying and the certificates chain is correct when I verify on the browser.
I can display the API ML page and Eureka page on the browser as well. So it seems the certificate has been generated correctly and why this messages appear in the log for the ZLUX.

Regards
Gilles Peniguel
                                                        
[zowe-setup-certificates-2022-12-15.log](https://github.com/zowe/zowe-install-packaging/files/10235429/zowe-setup-certificates-2022-12-15.log)
[zowe-setup-certificates-2022-12-15.txt](https://github.com/zowe/zowe-install-packaging/files/10235431/zowe-setup-certificates-2022-12-15.txt)

**Comment by GilPen** [comment]
Hello,


In fact, I install ZOWE on a reference partition and after I deploy MVS and ZFS files to the target partitions. 
I modify instance.env file according the new partition and generate the new certificates via the scripts zowe-setup-certificates.sh. 

In this situation, do I need to use the script "generate_zlux_certificates.sh" ? 

Regards
Gilles Peniguel

**Comment by GilPen** [comment]
Hello

The message "ZWED0061W - Callservice: Service call failed" appears.

I didn't see the ZWED0061W explanation in the documentation. Can you please explain this message ? 

Regards
Gilles Peniguel

**Comment by GilPen** [comment]
Hello

I close the ticket. The CA certificates was not tagged correctly.
