### ISSUE TITLE
Java 11 Test Cases

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#3329]
Add Java 11 test cases to the extended test suite, for Zowe v2. Zowe v1 will continue to be tested solely on Java 8.

Proposal:

- Add Java 11 base test case (install/verify)
- Add Java 11 keyring test case. 
   * Option 1: Run Java 11 keyring test case on all 3 security products
   * Option 2: Run Java 11 keyring on any security product (will likely rotate between all 3 over time).
   

With the above changes, the following cases are not covered with Java 11:
- VERIFY_CERTIFICATES
- External certificate import/verification
- Infinispan / VSAM Caching
- Extended install tests (PAX, SMP/e, PSWI, etc. on every system)

When Java 11 eventually becomes the default version for Zowe and Java 8 the configurable version, the coverage will be reversed. Java 11 will run with all test cases, and the above uncovered cases will impact Java 8.

**Comment by MarkAckert** [comment]
@achmelo Let me know if the plan proposed makes sense - and your preference for option 1 or option 2 with respect to keyring test cases.

**Comment by ojcelis** [comment]
Add new test cases for Java 11 but it fails in certificate steps see below.

```
2023-09-08T18:07:32.1241772Z [0;31m>>>> Import the Certificate Authority "local_ca" to the keystore "localhost":
2023-09-08T18:07:32.1241887Z [0m
2023-09-08T18:07:32.1242754Z [0;31m- Calling keytool -importcert -v -trustcacerts -noprompt -file /ZOWE/tmp/keystore/local_ca/local_ca.cer -alias local_ca -keystore /ZOWE/tmp/keystore/localhost/localhost.keystore.p12 -storepass password -storetype PKCS12
2023-09-08T18:07:32.1242877Z [0m
2023-09-08T18:07:32.1243058Z [0;31m  * keytool failed
2023-09-08T18:07:32.1243169Z [0m
2023-09-08T18:07:32.1243351Z [0;31m  * Exit code: 1
2023-09-08T18:07:32.1243462Z [0m
2023-09-08T18:07:32.1243622Z [0;31m  * Output:
2023-09-08T18:07:32.1243745Z [0m
2023-09-08T18:07:32.1244136Z [0;31m    keytool error: java.lang.Exception: Input not an X.509 certificate
2023-09-08T18:07:32.1244251Z [0m
2023-09-08T18:07:32.1244599Z [0;31m    java.lang.Exception: Input not an X.509 certificate
2023-09-08T18:07:32.1244714Z [0m
2023-09-08T18:07:32.1245180Z [0;31m    	at java.base/sun.security.tools.keytool.Main.addTrustedCert(Main.java:3112)
2023-09-08T18:07:32.1245303Z [0m
2023-09-08T18:07:32.1245732Z [0;31m    	at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1210)
2023-09-08T18:07:32.1245852Z [0m
2023-09-08T18:07:32.1246246Z [0;31m    	at java.base/sun.security.tools.keytool.Main.run(Main.java:416)
2023-09-08T18:07:32.1246360Z [0m
2023-09-08T18:07:32.1246756Z [0;31m    	at java.base/sun.security.tools.keytool.Main.main(Main.java:409)
```

PR new test cases: https://github.com/zowe/zowe-install-packaging/pull/3571
@achmelo currently looking into the issue.

**Comment by MarkAckert** [comment]
addressed in #3571 for v2

v3 testing is in Java 17 only
