### ISSUE TITLE
Install Java 17 on backend

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#3394]
We should install Java 17 on the backend test systems once its available for installation. Expected timeframe is 23Q3. This work should be started after #3396 to reduce the amount of system maintenance work.

**Comment by ojcelis** [comment]
Installed Java 17 on marist systems and add new test cases for Java 17 but it fails in certificate steps see below.

```
2023-09-08T18:07:32.1241772Z �[0;31m>>>> Import the Certificate Authority "local_ca" to the keystore "localhost":
2023-09-08T18:07:32.1241887Z �[0m
2023-09-08T18:07:32.1242754Z �[0;31m- Calling keytool -importcert -v -trustcacerts -noprompt -file /ZOWE/tmp/keystore/local_ca/local_ca.cer -alias local_ca -keystore /ZOWE/tmp/keystore/localhost/localhost.keystore.p12 -storepass password -storetype PKCS12
2023-09-08T18:07:32.1242877Z �[0m
2023-09-08T18:07:32.1243058Z �[0;31m  * keytool failed
2023-09-08T18:07:32.1243169Z �[0m
2023-09-08T18:07:32.1243351Z �[0;31m  * Exit code: 1
2023-09-08T18:07:32.1243462Z �[0m
2023-09-08T18:07:32.1243622Z �[0;31m  * Output:
2023-09-08T18:07:32.1243745Z �[0m
2023-09-08T18:07:32.1244136Z �[0;31m    keytool error: java.lang.Exception: Input not an X.509 certificate
2023-09-08T18:07:32.1244251Z �[0m
2023-09-08T18:07:32.1244599Z �[0;31m    java.lang.Exception: Input not an X.509 certificate
2023-09-08T18:07:32.1244714Z �[0m
2023-09-08T18:07:32.1245180Z �[0;31m    	at java.base/sun.security.tools.keytool.Main.addTrustedCert(Main.java:3112)
2023-09-08T18:07:32.1245303Z �[0m
2023-09-08T18:07:32.1245732Z �[0;31m    	at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1210)
2023-09-08T18:07:32.1245852Z �[0m
2023-09-08T18:07:32.1246246Z �[0;31m    	at java.base/sun.security.tools.keytool.Main.run(Main.java:416)
2023-09-08T18:07:32.1246360Z �[0m
2023-09-08T18:07:32.1246756Z �[0;31m    	at java.base/sun.security.tools.keytool.Main.main(Main.java:409)
```

PR new test cases: https://github.com/zowe/zowe-install-packaging/pull/3571
