### ISSUE TITLE
Errors in zlux-app-server log file

### ISSUE THREAD

**Issue by kiril-ibm** [zowe/zowe-install-packaging#361]
[2019-02-07 16:42:13.328 _zsf.bootstrap WARNING] - Implementation defaults for zosmf was not an object, or did not contain a plugins attribute. Other criteria for selecting authentication implementations is not yet implemented.
[2019-02-07 16:42:13.328 _zsf.bootstrap WARNING] - Authentication plugin was found which was not requested in the server configuration file's dataserviceAuthentication object. Skipping load of this plugin
[2019-02-07 16:42:13.328 _zsf.bootstrap WARNING] - /opt/zowe/zowe-1.0.0/zosmf-auth points to an invalid plugin definition, skipping
Error: Plugin org.zowe.zlux.auth.zosmf invalid
    at makePlugin (/opt/zowe/zowe-1.0.0/zlux-server-framework/lib/plugin-loader.js:508:11)
    at PluginLoader.installPlugins (/opt/zowe/zowe-1.0.0/zlux-server-framework/lib/plugin-loader.js:623:24)
    at PluginLoader.loadPlugins (/opt/zowe/zowe-1.0.0/zlux-server-framework/lib/plugin-loader.js:595:10)
    at Server.<anonymous> (/opt/zowe/zowe-1.0.0/zlux-server-framework/lib/index.js:177:23)
    at next (native)
    at tryCatcher (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2019-02-07 16:42:13.330 _zsf.bootstrap INFO] - Failed to load org.zowe.zlux.auth.zosmf: Error: Plugin org.zowe.zlux.auth.zosmf invalid
[2019-02-07 16:42:13.331 _zsf.bootstrap WARNING] - Implementation defaults for fallback was not an object, or did not contain a plugins attribute. Other criteria for selecting authentication implementations is not yet implemented.
[2019-02-07 16:42:13.331 _zsf.bootstrap WARNING] - Authentication plugin was found which was not requested in the server configuration file's dataserviceAuthentication object. Skipping load of this plugin
[2019-02-07 16:42:13.331 _zsf.bootstrap WARNING] - /opt/zowe/zowe-1.0.0/zlux-server-framework/plugins/trivial-auth points to an invalid plugin definition, skipping
Error: Plugin org.zowe.zlux.auth.trivial invalid
    at makePlugin (/opt/zowe/zowe-1.0.0/zlux-server-framework/lib/plugin-loader.js:508:11)
    at PluginLoader.installPlugins (/opt/zowe/zowe-1.0.0/zlux-server-framework/lib/plugin-loader.js:623:24)
    at PluginLoader.loadPlugins (/opt/zowe/zowe-1.0.0/zlux-server-framework/lib/plugin-loader.js:595:10)
    at Server.<anonymous> (/opt/zowe/zowe-1.0.0/zlux-server-framework/lib/index.js:177:23)
    at next (native)
    at tryCatcher (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/opt/zowe/zowe-1.0.0/zlux-server-framework/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[2019-02-07 16:42:13.332 _zsf.bootstrap INFO] - Failed to load org.zowe.zlux.auth.trivial: Error: Plugin org.zowe.zlux.auth.trivial invalid

**Comment by MarkAckert** [comment]
To my knowledge, these warnings refer to plugins which are in the plugins/ directory of zlux-app-server, but are not configured in the zluxserver.json file. This will not affect startup success for a default Zowe installation.  @1000TurquoisePogs @rpenny125 Are there short term solutions available - such as taking auth.trivial and auth.zosmf out of the default plugins/ dir, or reducing the log output / stacktrace?

**Comment by stevenhorsman** [comment]
I've had a look at the latest build's logs and am still seeing `ZWED0029W - Authentication plugin was found which was not requested in the server configuration file's dataserviceAuthentication object. Skipping load of this plugin`, but the message `Error: Plugin org.zowe.zlux.auth.zosmf invalid` is not there, so I think this issue can be closed now
